# Generated by Django 4.1.3 on 2022-11-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary_ts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandoa', models.CharField(max_length=150, verbose_name="Мандо'а")),
                ('russian', models.CharField(max_length=150, verbose_name='Русский')),
            ],
            options={
                'verbose_name': 'Словo',
                'verbose_name_plural': 'Слова',
            },
        ),
    ]
