# Generated by Django 4.1.3 on 2022-11-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandoa', models.CharField(max_length=150, verbose_name="Мандо'а")),
                ('prononciation', models.CharField(max_length=150, verbose_name='Произношение')),
                ('english', models.CharField(max_length=150, verbose_name='Английский')),
                ('russian', models.CharField(max_length=150, verbose_name='Русский')),
                ('part_of_speach', models.CharField(max_length=150, verbose_name='Часть речи')),
                ('written', models.CharField(max_length=150, verbose_name='Написание')),
                ('canon', models.CharField(max_length=150, verbose_name='Написание')),
                ('roots', models.CharField(max_length=150, verbose_name='ID корней')),
                ('date_load', models.DateField(verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Словo',
                'verbose_name_plural': 'Слова',
            },
        ),
        migrations.AlterModelOptions(
            name='dictionary_ts',
            options={'verbose_name': 'Словo_тест', 'verbose_name_plural': 'Слова_тест'},
        ),
    ]
