# Generated by Django 4.1.3 on 2022-11-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_dictionary_alter_dictionary_ts_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='canon',
            field=models.CharField(max_length=150, verbose_name='Канон'),
        ),
    ]
