# Generated by Django 4.1.3 on 2022-12-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_alter_dictionary_canon'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='tags',
            field=models.CharField(default='', max_length=1500, verbose_name='Тэги'),
            preserve_default=False,
        ),
    ]
