# Generated by Django 4.1.3 on 2022-12-25 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_dictionary_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionary_ts',
            options={'ordering': ['id'], 'verbose_name': 'Словo_тест', 'verbose_name_plural': 'Слова_тест'},
        ),
        migrations.RenameField(
            model_name='dictionary',
            old_name='prononciation',
            new_name='pronunciation',
        ),
    ]
