# Generated by Django 4.1.3 on 2023-01-04 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_remove_dictionary_roots_remove_dictionary_tags_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dictionary_ts',
        ),
    ]
