# Generated by Django 4.1.3 on 2023-01-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0009_alter_dictionary_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrasebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandoa', models.CharField(max_length=500, verbose_name="Мандо'а")),
                ('mandor', models.CharField(max_length=500, verbose_name='Мандор')),
                ('english', models.CharField(max_length=500, verbose_name='Английский')),
                ('comment_eng', models.CharField(max_length=150, verbose_name='Комментарий англ')),
                ('russian', models.CharField(max_length=500, verbose_name='Русский')),
                ('comment_rus', models.CharField(max_length=150, verbose_name='Комментарий англ')),
                ('canon', models.CharField(blank=True, max_length=150, null=True, verbose_name='Канон')),
                ('date_load', models.DateField(verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Фраза',
                'verbose_name_plural': 'Фразы',
                'ordering': ['id'],
            },
        ),
    ]
