# Generated by Django 4.1.3 on 2023-01-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0011_alter_phrasebook_canon_alter_phrasebook_comment_eng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrasebook',
            name='comment_eng',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Комментарий англ'),
        ),
        migrations.AlterField(
            model_name='phrasebook',
            name='comment_rus',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Комментарий англ'),
        ),
    ]
