# Generated by Django 4.1.3 on 2023-01-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0012_alter_phrasebook_comment_eng_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandoa', models.CharField(max_length=500, verbose_name="Мандо'а")),
                ('audio', models.FileField(upload_to='audio/')),
            ],
        ),
        migrations.AlterField(
            model_name='phrasebook',
            name='comment_rus',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Комментарий рус'),
        ),
    ]
