# Generated by Django 4.1.3 on 2023-01-23 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0013_audio_alter_phrasebook_comment_rus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audio',
        ),
    ]
