# Generated by Django 4.1.3 on 2023-01-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0014_delete_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandoa', models.CharField(max_length=500, verbose_name="Мандо'а")),
                ('audio', models.FileField(upload_to='audio/')),
            ],
        ),
    ]
